FROM python:3.8-slim

ADD database.py /
ADD etl.py /
ADD exceptions.py /
ADD query_provider.py /
ADD utils.py /

RUN python -m pip install --upgrade pip

RUN pip3 install pandas
RUN pip3 install psycopg2-binary

CMD ["python3", "etl.py"]