version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile-etl"
    container_name: "etl"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    command: python3 etl.py

  db:
    build:
        context: .
        dockerfile: "Dockerfile-db"
    container_name: "db"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_DATABASE"]
      interval: 10s
      timeout: 5s
      retries: 3